#!/bin/bash

DIR=/var/run/docker-monit/

set -ue
source /etc/default/docker-monit

echo "`date`: Starting docker-monit"
echo "`date`: containers = $CONTAINERS"

mkdir -p $DIR
cd $DIR

while :
do
  for name in $CONTAINERS
  do
    pid=`docker inspect -f '{{.State.Pid}}' $name 2>/dev/null || echo 0`
    if [ x$pid != '' -a $pid -ne 0 ]
    then
      echo $pid > $name.pid
    else
      rm -f $name.pid
    fi
  done
  sleep 10
done

